name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

    - name: Build Docker image
      run: docker build -t gen-3f327ca1-e4a4-436a-af49-5491f92fe082 .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/gen-3f327ca1-e4a4-436a-af49-5491f92fe082:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: k8s/*
        images: |
          user/gen-3f327ca1-e4a4-436a-af49-5491f92fe082:latest
        namespace: production
        kubectl-version: 'v1.18.0'